const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.site-nav');const footerSocial=document.querySelector('.footer-social .social-links');if(nav&&footerSocial){const mobileSocial=document.createElement('div');mobileSocial.className='mobile-social';mobileSocial.innerHTML='<p class="mobile-social-title">Follow Family First Equity Group</p>';const mobileLinks=footerSocial.cloneNode(true);mobileLinks.setAttribute('aria-label','Family First Equity Group social media');mobileSocial.appendChild(mobileLinks);nav.appendChild(mobileSocial)}if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu');document.body.classList.toggle('nav-open',open)});nav.querySelectorAll('a:not([href="#"])').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open menu');document.body.classList.remove('nav-open')}))}document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());

document.querySelectorAll('[data-property-coming-soon]').forEach((button)=>button.addEventListener('click',()=>{alert('Property details are coming soon. No active property listing is available at this time.')}));

document.querySelectorAll('[data-credit-help-select]').forEach((select)=>{const form=select.closest('form');const message=form?form.querySelector('[data-credit-help-message]'):null;if(!message)return;const update=()=>{message.hidden=select.value!=='Yes'};select.addEventListener('change',update);update()});

const FFEG_DB_URL='https://jgpvrblzyznyprtffirw.supabase.co';
const FFEG_PUBLIC_DB_KEY='ADD_PUBLIC_SUPABASE_KEY_HERE';

function getField(form,name){const item=form.elements[name];if(!item)return'';if(item instanceof RadioNodeList){return Array.from(item).filter(el=>el.checked).map(el=>el.value).join(', ')}if(item.type==='file'){return item.files&&item.files.length?item.files.length+' uploaded file(s) saved by the website form record':''}return item.value||''}
function formSummary(form){const lines=[];new FormData(form).forEach((value,key)=>{if(key==='bot-field'||key==='form-name')return;if(value instanceof File){if(value.name)lines.push(key+': '+value.name)}else{lines.push(key+': '+value)}});return lines.join('\n')}
function loadDb(){return new Promise((resolve,reject)=>{if(window.supabase)return resolve(window.supabase.createClient(FFEG_DB_URL,FFEG_PUBLIC_DB_KEY));const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=()=>resolve(window.supabase.createClient(FFEG_DB_URL,FFEG_PUBLIC_DB_KEY));script.onerror=reject;document.head.appendChild(script)})}
function sellerRow(form){return{source:'family_first_website',full_name:(getField(form,'first_name')+' '+getField(form,'last_name')).trim(),phone:getField(form,'phone'),email:getField(form,'email'),property_address:[getField(form,'property_address'),getField(form,'city'),getField(form,'state'),getField(form,'zip_code')].filter(Boolean).join(', '),reason_for_selling:getField(form,'selling_reason')||getField(form,'desired_outcome'),urgency:getField(form,'selling_timeline')||getField(form,'meeting_availability'),notes:formSummary(form),status:'new'}}
function managementRow(form){return{company:'Family First',caller_name:(getField(form,'first_name')+' '+getField(form,'last_name')).trim(),phone:getField(form,'phone'),email:getField(form,'email'),reason_for_call:'Property management website request',property_address:[getField(form,'property_address'),getField(form,'city'),getField(form,'state'),getField(form,'zip')].filter(Boolean).join(', '),assigned_department:'Property Management Department',ai_receptionist_notes:formSummary(form),status:'new'}}
async function saveLeadToDashboard(form){if(!FFEG_PUBLIC_DB_KEY||FFEG_PUBLIC_DB_KEY==='ADD_PUBLIC_SUPABASE_KEY_HERE')return;const db=await loadDb();const name=(form.getAttribute('name')||'').toLowerCase();if(name.includes('seller'))await db.from('seller_leads').insert(sellerRow(form));if(name.includes('property-management'))await db.from('phone_leads').insert(managementRow(form))}
document.querySelectorAll('form[data-netlify="true"]').forEach(form=>{form.addEventListener('submit',()=>{saveLeadToDashboard(form).catch(err=>console.warn('Dashboard lead save issue:',err))})});
